language: csharp
mono: none
dotnet: 2.1
env:
 - CONFIGURATION=Release
script:
 - cd ./NiL.JS
 - dotnet clean
 - dotnet restore
 - dotnet build
 - cd ../IntegrationTests
 - dotnet test 
 - cd ../FunctionalTests
 - dotnet ../Utility/tt4/tiny-t4.dll
 - dotnet test 