name: .NET Core

on: [push]

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core 2.1.804
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.804

    - name: Setup .NET Core 3.1.102
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102

    - name: Setup side by side .NET SDKs on *nix
      if: matrix.os != 'windows-latest'
      run: |
        rsync -a ${DOTNET_ROOT/3.1.102/2.1.804}/* $DOTNET_ROOT/

    - run: dotnet --info

    - name: Restore
      run: |
        dotnet restore ./Tests.sln

    - name: Build
      run: |
        dotnet build --no-restore ./Tests.sln

    - name: Test
      run: |
        dotnet test --no-build ./Tests.sln
